site_name: 全息记录仪
site_description: 搭建中
site_url: https://Palpatine666666.github.io
site_author: 帕尔帕廷
repo_name: Palpatine666666  #存储库名称，一般自动设置
repo_url: https://github.com/Palpatine666666/Palpatine666666.github.io  #存储库URL
copyright: Copyright &copy; 2025 <a href="https://github.com/Palpatine666666"  target="_blank" rel="noopener">Palpatine666666</a>

#主题
theme:  
  name: material
  language: zh
  #图标
  logo: assets/octagram-white.svg
  favicon: assets/octagram.svg
  icon: 
    repo: fontawesome/brands/empire
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    # - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  # 字体（后有css）
  font: 
    text: SimSun
    code: Consolas
    
  # 配色方案：默认模式
  palette:  
    # 浅色模式
    - scheme: default
      accent: deep purple
      toggle:
        icon: fontawesome/brands/sith
        name: Dark side
 
    # 深色模式
    - scheme: slate
      accent: deep purple
      toggle:
        icon: fontawesome/brands/jedi
        name: Light side

  #插件
  markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - footnotes
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - abbr
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences  # 代码块高亮插件
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight: #代码块高亮
      anchor_linenums: true
      auto_title: true # 显示编程语言名称
      # linenums: true # 显示行号
  - pymdownx.arithmatex:  #LaTeX支持
      generic: true

#搜索
plugins:
  - search: 
      lang:
        - zh
        - en
  - tags
  - git-revision-date-localized:
      enabled: true
      type: date
      locale: zh
      exclude:
        - index.md
  - open-in-new-tab:
   
#java
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#css
extra_css: 
  - css/fonts.css #字体设置英文Times New Roman，中文宋体

#
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Palpatine666666
  analytics:
    provider: google
    property: G-0CRMN4K682
  


#导航
nav:
  - 主页:
    - index.md
    - 收藏夹: 
      - 主页/收藏夹/index.md
      - 托尔金相关: 主页/收藏夹/托尔金相关.md
  - 阿尔达:
    - 昆雅语:
      - Quenya Course:
        - 阿尔达/昆雅语/Quenya Course/index.md
        - intro: 阿尔达/昆雅语/Quenya Course/绪论.md
      - Speak Elf Yourself: 
        - 阿尔达/昆雅语/Speak Elf Yourself/index.md
        - Part 1 Introduction: 阿尔达/昆雅语/Speak Elf Yourself/Part 1 Introduction.md
        - Part 2 The quenya vowels: 阿尔达/昆雅语/Speak Elf Yourself/Part 2 The quenya vowels.md
        - Part 3 Plurals and special stem-forms: 阿尔达/昆雅语/Speak Elf Yourself/Part 3 Plurals and special stem-forms.md
    - 阿尔达野史:
      - 阿尔达/阿尔达野史/index.md
      - 万恶之源: 阿尔达/阿尔达野史/万恶之源.md
      - 礼崩乐坏: 阿尔达/阿尔达野史/礼崩乐坏.md
      - 意外发现: 阿尔达/阿尔达野史/意外发现.md
      - 未解之谜: 阿尔达/阿尔达野史/未解之谜.md
  - 异星歧途:
    - 异星歧途/index.md
    - Mkdocs部署: 异星歧途/Mkdocs.md
  - 数学笔记:
      - 分析: 数学笔记/分析.md

