site_name: 帕尔帕廷的全息记录仪
site_url: https://Palpatine666666.github.io
site_author: 帕尔帕廷

#主题
theme:  
  name: material
  language: zh

#导航
nav:
  - 主页: "主页.md"
  - Home: index.md
  - Tec: Mkdocs部署.md
  - 阿尔达漫游: 
    - 昆雅语: "阿尔达漫游/昆雅语/Speak Elf Yourself笔记.md"